# Generated by Django 5.2.8 on 2025-11-15 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('checked_out', 'Checked out'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('lost', 'Lost'), ('damaged', 'Damaged')], default='reserved', max_length=20)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('game_copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_records', to='games.gamecopy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExtensionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('new_due_date', models.DateTimeField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rental_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_requests', to='rentals.rentalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='DamageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('damage_photos', models.ImageField(blank=True, null=True, upload_to='damage_photos/')),
                ('status', models.CharField(choices=[('ok', 'No issue'), ('damaged', 'Damaged'), ('missing_pieces', 'Missing pieces'), ('lost', 'Lost')], default='ok', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('replacement_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('rental_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_reports', to='rentals.rentalrecord')),
            ],
        ),
    ]
