# Generated by Django 5.2.8 on 2025-11-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='active_rentals_available',
            field=models.IntegerField(default=2),
        ),
    ]
